name: Run Daily Script

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

  workflow_dispatch: # Allows manual triggering of the workflow
    inputs: {}

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Use the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure your repository has a requirements.txt file

      # Run the script
      - name: Run the script
        run: python /path/to/0.RunAll.py
